version: '3.4'
services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'fashion'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./docker/db:/var/lib/mysql
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   ports:
  #     - '8088:80'
  #   links:
  #     - db
  #   environment:
  #     - PMA_ARBITRARY=1
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: 'web_dat_ve_xe_khach'
    ports:
      - 8000:8000
    command: sh docker/docker-entrypoint.sh
    volumes:
      - ./:/var/www/html
